# Generated by Django 3.1.7 on 2021-04-07 04:12

import csvs.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='csvs', validators=[csvs.validator.validate_file_size]),
        ),
    ]
