# Generated by Django 3.1.7 on 2021-05-05 03:05

import csvs.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('file_name', models.FileField(upload_to='store', validators=[csvs.validator.validate_file_size])),
            ],
        ),
    ]
