# Generated by Django 3.1.7 on 2021-05-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
