# Generated by Django 3.1.7 on 2021-04-07 03:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCollection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('add_date', models.DateField(blank=True, default=datetime.datetime.now, editable=False)),
                ('last_accessed', models.DateField(blank=True, editable=False, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['add_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=45)),
                ('definition', models.TextField()),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='wordbook.vocabularycollection')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('memory_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_count', models.IntegerField(blank=True, default=0)),
                ('incorrect_count', models.IntegerField(blank=True, default=0)),
                ('last_correct', models.DateField(blank=True, default=datetime.datetime.now)),
                ('last_incorrect', models.DateField(blank=True, default=datetime.datetime.now)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='wordbook.word')),
            ],
            options={
                'ordering': ['correct_count'],
            },
        ),
        migrations.AddConstraint(
            model_name='vocabularycollection',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_vocabulary_collection'),
        ),
    ]
