# Generated by Django 3.1.7 on 2021-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vocabularycollection',
            name='unique_vocabulary_collection',
        ),
        migrations.AddConstraint(
            model_name='vocabularycollection',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'category'), name='unique_vocabulary_collection'),
        ),
    ]
