# Generated by Django 3.1.7 on 2021-04-16 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbook', '0002_auto_20210407_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('correctness', models.BooleanField()),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='wordbook.word')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
