# Generated by Django 3.1.7 on 2021-04-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0003_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
